AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  tezos-in-memory-signer-lambda

  An in-memory signer for Tezos based on Taquito.
  
Globals:
  Function:
    Timeout: 3
    Runtime: nodejs18.x

Parameters:
  BakerAuthorizedKey:
    Type: String
    Description: The authorized key for the signer. This must be a Tezos-encoded public key.
  SecretKey:
    Type: String
    Description: The secret key used for signing. This must be a Tezos-encoded private key.
  SecretUrlPath:
    Type: String
    Description: The secret URL path to the signer.

Resources:
  TaquitoSignerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: taquito-signer/
      Handler: index.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      # Events:
      #   HttpApi:
      #     Type: Api
      #     Properties:
      #       Path: /sign
      #       Method: post
      Environment: # Environment variables configuration
        Variables:
          SECRET_KEY: !Ref SecretKey
          BAKER_AUTHORIZED_KEY: !Ref BakerAuthorizedKey
          SECRET_URL_PATH: !Ref SecretUrlPath
      FunctionUrlConfig:
        AuthType: NONE

# Outputs:
#   TaquitoSignerFunctionUrl:
#     Description: "URL of the signer"
#     Value: !GetAtt TaquitoSignerFunction.FunctionUrl
