AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  tezos-in-memory-signer-lambda

Globals:
  Function:
    Timeout: 3
    Runtime: nodejs18.x

Resources:
  TezosApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod

  # Resource and method for /abc123/authorized_keys
  AuthorizedKeysResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref TezosApi
      ParentId: !GetAtt TezosApi.RootResourceId
      PathPart: authorized_keys

  AuthorizedKeysMock:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref TezosApi
      ResourceId: !Ref AuthorizedKeysResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates:
              application/json: '{}'

  # Lambda function with API event
  TaquitoSignerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: taquito-signer/
      Handler: index.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        KeysPost:
          Type: Api
          Properties:
            RestApiId: !Ref TezosApi
            Path: /abc123/keys/tz1XfNWYxfKRskaEZxytFJ3WXagcb7XJ6g76
            Method: post

