AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  tezos-in-memory-signer-lambda

Globals:
  Function:
    Timeout: 3
    Runtime: nodejs18.x

Parameters:
  BakerAuthorizedKey:
    Type: String
    Description: The authorized key for the signer. This must be a Tezos-encoded public key.
  SecretKey:
    Type: String
    Description: The secret key used for signing. This must be a Tezos-encoded private key.
Resources:
  TaquitoSignerConfigurator:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: signer-configurator/
      Handler: index.handler
      Runtime: nodejs18.x
      Environment:
        Variables:
          SECRET_KEY: !Ref SecretKey

  SignerLambdaEnv:
    Type: Custom::SignerLambdaEnv
    Properties:
      ServiceToken: !GetAtt TaquitoSignerConfigurator.Arn

  TezosApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: TezosApi

  RandomPathResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref TezosApi
      ParentId: !GetAtt TezosApi.RootResourceId
      PathPart: !GetAtt SignerLambdaEnv.randomString

  AuthorizedKeysResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref TezosApi
      ParentId: !Ref RandomPathResource
      PathPart: authorized_keys
  AuthorizedKeysMock:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref TezosApi
      ResourceId: !Ref AuthorizedKeysResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates:
              application/json: '{}'
      MethodResponses:
      - StatusCode: 200
        ResponseModels:
          application/json: 'Empty'
  KeysResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref TezosApi
      ParentId: !Ref RandomPathResource
      PathPart: keys

  SpecificKeyResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref TezosApi
      ParentId: !Ref KeysResource
      PathPart: !GetAtt SignerLambdaEnv.publicKeyHash

  SpecificKeyGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref TezosApi
      ResourceId: !Ref SpecificKeyResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates:
              application/json: '{"public_key": "edpkv5rSnqqQpUh8Zx3fkaH4EGQDSaUD2aPVxcsi2gtwZtYaThs5kV"}'
      MethodResponses:
      - StatusCode: 200
        ResponseModels:
          application/json: 'Empty'

  SpecificKeyPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref TezosApi
      ResourceId: !Ref SpecificKeyResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TaquitoSignerFunction.Arn}/invocations
        IntegrationHttpMethod: POST

  TaquitoSignerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: taquito-signer/
      Handler: index.handler
      Runtime: nodejs18.x
      Environment: # Environment variables configuration
        Variables:
          SECRET_KEY: !Ref SecretKey
          BAKER_AUTHORIZED_KEY: !Ref BakerAuthorizedKey
          
  TaquitoSignerFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt TaquitoSignerFunction.Arn
      Principal: apigateway.amazonaws.com

  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - AuthorizedKeysMock
      - SpecificKeyPostMethod
    Properties:
      RestApiId: !Ref TezosApi
      Description: 'API deployment for tezos-in-memory-signer-lambda'

  ApiGatewayStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: prod
      RestApiId: !Ref TezosApi
      DeploymentId: !Ref ApiGatewayDeployment

