AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  tezos-in-memory-signer-lambda

Globals:
  Function:
    Timeout: 3
    Runtime: nodejs18.x

Resources:
  TezosApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: TezosApi

  Abc123Resource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref TezosApi
      ParentId: !GetAtt TezosApi.RootResourceId
      PathPart: abc123

  AuthorizedKeysResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref TezosApi
      ParentId: !Ref Abc123Resource
      PathPart: authorized_keys

  AuthorizedKeysMock:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref TezosApi
      ResourceId: !Ref AuthorizedKeysResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates:
              application/json: '{}'

  KeysResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref TezosApi
      ParentId: !Ref Abc123Resource
      PathPart: keys

  SpecificKeyResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref TezosApi
      ParentId: !Ref KeysResource
      PathPart: tz1XfNWYxfKRskaEZxytFJ3WXagcb7XJ6g76

  SpecificKeyPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref TezosApi
      ResourceId: !Ref SpecificKeyResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TaquitoSignerFunction.Arn}/invocations
        IntegrationHttpMethod: POST

  TaquitoSignerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: taquito-signer/
      Handler: index.handler
      Runtime: nodejs18.x

  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - AuthorizedKeysMock
      - SpecificKeyPostMethod
    Properties:
      RestApiId: !Ref TezosApi
      Description: 'API deployment for tezos-in-memory-signer-lambda'

  ApiGatewayStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: prod
      RestApiId: !Ref TezosApi
      DeploymentId: !Ref ApiGatewayDeployment

